# Generated by Django 5.2.5 on 2025-09-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('Rut', models.IntegerField()),
                ('Nom_ap', models.CharField(max_length=45)),
                ('Telefono', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMas', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMascota', models.CharField(max_length=45)),
                ('Animal', models.CharField(max_length=45)),
                ('Raza', models.CharField(max_length=45)),
                ('chip', models.IntegerField()),
                ('idCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vet1.cliente')),
            ],
        ),
    ]
